# Generated by Django 6.0 on 2025-12-15 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.CharField(max_length=50)),
                ('q2', models.CharField(max_length=10)),
                ('q3', models.CharField(max_length=10)),
                ('q4', models.CharField(max_length=10)),
                ('q5', models.CharField(max_length=10)),
                ('q6', models.CharField(max_length=10)),
                ('q7', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mood', models.CharField(blank=True, max_length=20, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
        ),
    ]
