# Generated by Django 6.0 on 2025-12-15 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customerquiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='meal',
            options={'verbose_name': 'Meal', 'verbose_name_plural': 'Meals'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'Restaurant', 'verbose_name_plural': 'Restaurants'},
        ),
        migrations.DeleteModel(
            name='CustomerQuiz',
        ),
    ]
